const Discord = require('discord.js');

module.exports = {
	name: 'rules',
	description: 'Get rules for the server',
	execute(message, args) {
        // https://discohook.org/?message=eyJtZXNzYWdlIjp7ImNvbnRlbnQiOiJcbiIsImVtYmVkcyI6W3siY29sb3IiOjM5NDIzLCJpbWFnZSI6eyJ1cmwiOiJodHRwczovL2dpdGh1Yi5jb20vQksxMDMxL0ltYWdlQXNzZXRzL2Jsb2IvbWFzdGVyL3J1bGVzLWwucG5nP3Jhdz10cnVlIn19LHsidGl0bGUiOiJHZW5lcmFsIFJ1bGVzIiwiZGVzY3JpcHRpb24iOiIqKlJ1bGUgMToqKiBGb2xsb3cgdGhlIFwiZ29sZGVuIHJ1bGVcIi4gQmUgcmVzcGVjdGZ1bCBhbmQgaGVscCBtYWtlIHRoaXMgYSBwb3NpdGl2ZSBlbnZpcm9ubWVudCB3aGVyZSBwZW9wbGUgY2FuIGxlYXJuIGFuZCBncm93LlxuXG4qKlJ1bGUgMjoqKiBGb2xsb3cgYWxsIGNoYW5uZWwgbmFtZXMvdG9waWNzLiBLZWVwIGNvbnZlcnNhdGlvbnMgcmVsZXZhbnQgdG8gdGhlaXIgcmVzcGVjdGl2ZSBjaGFubmVscy5cblxuKipSdWxlIDM6KiogQW5ndWxhciBzdWNrcyBhbmQgaXMgaW5mZXJpb3IgdG8gUmVhY3QsIHdoaWNoIHN1Y2tzIGFuZCBpcyBpbmZlcmlvciB0byBGbHV0dGVyLCBkbyBub3QgdGhpbmsgeW91IGtub3cgb3RoZXJ3aXNlLlxuXG4qKlJ1bGUgNDoqKiBEbyBub3QgbWVudGlvbiBmZWRlcmFsIGFnZW50cyBvciBzZXJ2ZXIgb2ZmaWNpYWxzICg8QCY2NzQzMTg4NDQzMzE5NTAxMDI-LCA8QCY3MDI3NzE3MDEyMTcyMzA5MTk-KSB1bmxlc3MgeW91IGhhdmUgYSBnb29kIHJlYXNvbiB0by5cblxuKipSdWxlIDU6KiogRG8gbm90IGltcGVyc29uYXRlIGEgZmVkZXJhbCBhZ2VudCBvciBvdGhlciBzZXJ2ZXIgb2ZmaWNpYWwuXG5cbioqUnVsZSA2OioqIFJlZnJhaW4gZnJvbSBzcGFtbWluZywgd2hldGhlciBpdHMgaW4gdGV4dCBjaGFubmVscyBvciBlYXJyYXBlIGluIHZvaWNlIGNoYW5uZWxzLlxuXG4qKlJ1bGUgNzoqKiAgRG8gbm90IG9yZ2FuaXplLCBwYXJ0aWNpcGF0ZSBpbiwgb3IgZW5jb3VyYWdlIGhhcmFzc21lbnQgb2Ygb3RoZXJzLlxuXG4qKlJ1bGUgODoqKiBEbyBub3QgbWFrZSB0aHJlYXRzIG9mIHZpb2xlbmNlIG9yIHRocmVhdGVuIHRvIGhhcm0gb3RoZXJzLlxuXG4qKlJ1bGUgOToqKiBZb3UgbXVzdCBrZWVwIGFsbCBOU0ZXIGNvbnRlbnQgaW4gdGhlIGNvcnJlY3QgTlNGVyBsYWJlbGVkIGNoYW5uZWwocykuXG5cbioqUnVsZSAxMDoqKiBQbGVhc2UgYmUgbWluZGZ1bCBvZiBvdGhlcnMgd2hlbiBzaGFyaW5nIGNvbnRlbnQgdGhhdCBqb2tlcyBhYm91dCBhbnl0aGluZyBpbiBnZW5lcmFsLCBidXQgZXNwZWNpYWxseSB3aGVuIGl0J3MgYWJvdXQgc3VpY2lkZSBvciBzZWxmLWhhcm0uIiwiY29sb3IiOjM5NDIzfSx7InRpdGxlIjoiUnVsZSBJbmZyYWN0aW9ucyIsImRlc2NyaXB0aW9uIjoiVGhlcmUgaXMgbm8gc2V0IG9yZGVyIG9mIHB1bmlzaG1lbnRzIGZvciBydWxlIHZpb2xhdGlvbnMuIElmIHlvdSBkbyBkZWNpZGUgdG8gZ28gZG93biB0aGlzIGRhcmsgcm9hZCwgdGhlcmUgd2lsbCB1c3VhbGx5IGJlIDEgb3IgMiB3YXJuaW5ncyBiZWZvcmUgYmVpbmcgbXV0ZWQuIENvbnNpc3RlbnQgcnVsZS1icmVha2luZyB3aWxsIHJlc3VsdCBpbiBhIHRlbXAtYmFuIGFuZCBldmVudHVhbCBwZXJtLWJhbi5cblxuRmVkZXJhbCBhZ2VudHMgaGF2ZSB0aGUgZmluYWwgaW50ZXJwcmV0YXRpb24gb2YgYW55IHJ1bGUsIGFuZCBjYW4gYXNzaWduIHB1bmlzaG1lbnRzIGF0IHRoZWlyIGRpc2NyZXRpb24uIEV2ZW4gcnVsZXMgdGhhdCBoYXZlIGEgcHJlY2VkZW50IGZvciBob3cgdGhleSBhcmUgZW5mb3JjZWQgY2FuIGJlIGludGVycHJldGVkIGRpZmZlcmVudGx5IGxhdGVyIG9uLiBUaGlzIHJ1bGUgaXMgbWVhbnQgdG8gY292ZXIgYW55IGdhcHMgb3IgbG9vcGhvbGVzIHRoYXQgbWF5IGJlIGZvdW5kIGluIHRoZSBydWxlcy4gSWYgeW91IGRpc2FncmVlIHdpdGggdGhlIHdheSBhIGZlZGVyYWwgYWdlbnQgaGFzIGhhbmRsZWQgeW91ciBjYXNlLCB5b3UgbWF5IHBvbGl0ZWx5IGFwcGVhbCBmaWxlIGFuIGFwcGVhbCB3aXRoIHRoZSA8QCY3MDI3NzE3MDEyMTcyMzA5MTk-LiIsImNvbG9yIjozOTQyM30seyJjb2xvciI6Mzk0MjMsImF1dGhvciI6eyJuYW1lIjoiQksxMDMxIFBsYXlncm91bmQgU2VydmVyIFJ1bGVzIiwidXJsIjoiaHR0cHM6Ly9iazEwMzEuZGV2L2Rpc2NvcmQtcnVsZXMifSwiZm9vdGVyIjp7InRleHQiOiJMYXN0IFVwZGF0ZWQifSwidGltZXN0YW1wIjoiMjAyMC0wOC0xNVQwNzowNzowMC4wMDBaIn1dfX0
		message.channel.send(new Discord.MessageEmbed()
			.setColor('#0099ff')
            .setImage("https://github.com/BK1031/ImageAssets/blob/master/rules-l.png?raw=true")
        );
        message.channel.send(new Discord.MessageEmbed()
            .setColor('#0099ff')
            .setTitle("General Rules")
            .setDescription("**Rule 1:** Follow the \"golden rule\". Be respectful and help make this a positive environment where people can learn and grow.\n\n**Rule 2:** Follow all channel names/topics. Keep conversations relevant to their respective channels.\n\n**Rule 3:** Angular sucks and is inferior to React, which sucks and is inferior to Flutter, do not think you know otherwise.\n\n**Rule 4:** Do not mention federal agents or server officials (<@&674318844331950102>, <@&702771701217230919>) unless you have a good reason to.\n\n**Rule 5:** Do not impersonate a federal agent or other server official.\n\n**Rule 6:** Refrain from spamming, whether its in text channels or earrape in voice channels.\n\n**Rule 7:**  Do not organize, participate in, or encourage harassment of others.\n\n**Rule 8:** Do not make threats of violence or threaten to harm others.\n\n**Rule 9:** You must keep all NSFW content in the correct NSFW labeled channel(s).\n\n**Rule 10:** Please be mindful of others when sharing content that jokes about anything in general, but especially when it's about suicide or self-harm.")
        );
        message.channel.send(new Discord.MessageEmbed()
            .setColor('#0099ff')
            .setTitle("Rule Infractions")
            .setDescription("There is no set order of punishments for rule violations. If you do decide to go down this dark road, there will usually be 1 or 2 warnings before being muted. Consistent rule-breaking will result in a temp-ban and eventual perm-ban.\n\nFederal agents have the final interpretation of any rule, and can assign punishments at their discretion. Even rules that have a precedent for how they are enforced can be interpreted differently later on. This rule is meant to cover any gaps or loopholes that may be found in the rules. If you disagree with the way a federal agent has handled your case, you may politely appeal file an appeal with the <@&702771701217230919>.")
        );
        message.channel.send(new Discord.MessageEmbed()
            .setAuthor("BK1031 Playground Server Rules", null, "https://bk1031.dev/discord-rules")
            .setFooter("Last Updated")
            .setTimestamp()
        );
	},
};